########################################################################################

# This Makefile generated by GoMakeGen 0.5.0 using next command:
# gomakegen .

########################################################################################

.PHONY = fmt deps deps-test test

########################################################################################

deps:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v8

deps-test:
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/check.v1
	go get -d -v pkg.re/essentialkaos/ek.v8

test:
	go test -covermode=count .

fmt:
	find . -name "*.go" -exec gofmt -s -w {} \;

########################################################################################
